# Generated by Django 5.2.1 on 2025-05-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0002_cinemahall_cinema_seat_cinema_hall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinema',
            old_name='locations',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('VIP', 'Vip'), ('STANDARD', 'Standard'), ('PROMO', 'Promo'), ('WHEELCHAIR', 'Wheelchair'), ('SUPER_PROMO', 'Super Promo')], default='STANDARD'),
        ),
    ]
