# Generated by Django 5.2.1 on 2025-05-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
