# Generated by Django 5.2.1 on 2025-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0006_alter_showtime_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
