# Generated by Django 5.2.1 on 2025-05-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_alter_booking_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
