# Generated by Django 5.2.1 on 2025-05-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0008_alter_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('cinema_hall', 'number')},
        ),
    ]
