# Generated by Django 5.2.1 on 2025-05-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0009_alter_seat_number_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cinemahall',
            unique_together={('hall_number', 'cinema')},
        ),
    ]
