# Generated by Django 5.2.1 on 2025-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0010_alter_cinemahall_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
