# Generated by Django 5.2.1 on 2025-05-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0011_alter_booking_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
