# Generated by Django 5.2.1 on 2025-05-25 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0012_booking_payment_status_alter_booking_purchase_date'),
        ('userAuth', '0002_remove_profile_bookings_remove_profile_total_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userAuth.profile'),
        ),
    ]
