# Generated by Django 5.2.1 on 2025-05-25 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0013_remove_booking_user_booking_profile'),
        ('userAuth', '0002_remove_profile_bookings_remove_profile_total_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='userAuth.profile'),
        ),
    ]
